config/routes.rb
Rails.application.routes.draw do
  get 'pages/test'

  root 'pages#test'

  match "/auth/twitter/callback" => "sessions#create", :via => [:get], :as => 'sessions_create'
  match "/signout" => "sessions#destroy", :via => [:get], :as => :signout

end

app/models/user.rb
class User < ActiveRecord::Base
	def self.create_with_omniauth(auth)
		create! do |user|
			user.provider = auth["provider"]
			user.uid = auth["uid"]
			user.name = auth["info"]["name"]
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  private

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def test
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
		auth = request.env["omniauth.auth"]
		user = User.find_by_provider_and_uid(auth["provider"],["uid"]) || User.create_with_omniauth(auth)
		session[:user_id] = user.id
		redirect_to root_url, :notice => "Signed In!"
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_url, :notice => "Signed Out!"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitterapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% if current_user %>
		Welcome <%= current_user.name %>!
		<%= link_to "Sign Out", signout_path %>
	<% else %>
		<%= link_to "Sign in with Twitter", "/auth/twitter" %>
	<% end %>
<%= flash.each do |name, msg| %>
	<%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>
<%= yield %>

</body>
</html>

app/views/pages/test.html.erb
<h1>Pages#test</h1>
<p>Find me in app/views/pages/test.html.erb</p>